#!/bin/sh
convert $1 -resize '1024x768>' $1_resized
convert $1_resized -colorspace Gray -depth 3 -sample 50% -sample 200% png:- | \
  composite -tile filter/mask.png - -compose Linear_Dodge png:- | \
  convert - -fuzz 8% -transparent white png:-
